# Generated by Django 5.0.3 on 2024-03-19 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_club_leader'),
        ('users', '0003_alter_user_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club_id',
        ),
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club', to='clubs.club'),
        ),
    ]
