# Generated by Django 5.0.3 on 2024-03-19 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_club_leader_alter_club_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
