# Generated by Django 5.0.3 on 2024-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_club_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
