# Generated by Django 5.0.3 on 2024-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.ImageField(null=True, upload_to='club_icons/'),
        ),
    ]
