# Generated by Django 5.0.3 on 2024-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_club_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
