# Generated by Django 5.0.3 on 2024-03-20 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_club_created_club_is_approved_club_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
