# Generated by Django 5.0.3 on 2024-03-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_created_alter_clubjoinrequest_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
